### ISSUE TITLE
How to move?

### ISSUE THREAD

**Issue by winkler1** [macaco-maluco/birinto#1]
This looks cool...but how do you move? I've tried keyboard, mouse, touching on ipad...nothing has worked. I see from https://github.com/macaco-maluco/birinto/blob/master/lib%2Fgame-screen.jsx that it's touch, but not working.

**Comment by pirelenito** [comment]
Hi @winkler1 

That is weird, it should work on touch devices. On a screen with no touch you simply move the mouse cursor to the next step you want to go.

It starts on the green spot, and your objective is the gold one.

Here is a video of it in action: https://www.youtube.com/watch?v=5Z04I65kDSI

Did it help?

**Comment by winkler1** [comment]
Nope, doesn't work in safari on ipad.

**Comment by winkler1** [comment]
or emulating an iphone in Chrome.

**Comment by winkler1** [comment]
Hi, any ideas? Feel like I cannot feature this on react.rocks unless the moving works.

**Comment by pirelenito** [comment]
Hi @winkler1 I am not sure how to help.

We've been doing testing on multiple devices since launch and we haven't seen the problem you've described.

Here is a video of it working on Chrome: https://www.youtube.com/watch?v=KQKYXhIRwbs

What version of iOS are you using? Are you getting any errors on your console?

**Comment by pirelenito** [comment]
Hi @winkler1 are you trying to run it locally or through our "production" deployment http://ss15-macaco-maluco.divshot.io/#/ ?

**Comment by winkler1** [comment]
Hi- through the divshot deployment. Just tried in chrome/ipad emulation,
and on ipad. No movement.

On Wed, Mar 18, 2015 at 3:45 PM, Paulo Ragonha notifications@github.com
wrote:

> Hi @winkler1 https://github.com/winkler1 are you trying to run it
> locally or through our "production" deployment
> http://ss15-macaco-maluco.divshot.io/#/ ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/macaco-maluco/birinto/issues/1#issuecomment-83137917.

## 

http://twitter.com/#!/winkler1
Co-organizer, ReactJS Boston http://www.meetup.com/ReactJS-Boston/

**Comment by pirelenito** [comment]
Could we talk it over Hangouts? Or maybe, could you make a screencast/video of you testing the game to help us understand the problem? My email is paulo @ ragonha.me

**Comment by pirelenito** [comment]
Closing this issue since there was no more updates.
