### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by pirelenito** [macaco-maluco/birinto#3]
Build on Travis a docker image `macacomaluco/birinto:latest` that will contain an Nginx inside serving the built static assets.

We should have only the static assets and Nginx inside the Docker image, which means we will probably need to have the static assets built first and then the Docker image.

For a reference, I've started working on https://github.com/macaco-maluco/pressora/pull/1

**Comment by pirelenito** [comment]
@maxcnunes would you like to do this one?

**Comment by maxclaus** [comment]
@pirelenito sure!

**Comment by pirelenito** [comment]
I managed to get the other project to build!

**Comment by pirelenito** [comment]
We recently made the landing page http://macacomaluco.space/

It is also a static page. Check its implementation for inspiration: https://github.com/macaco-maluco/macaco-maluco/commit/e199a2204b4aaef84d981b137ed096e9a4fe6737

**Comment by pirelenito** [comment]
@maxcnunes 

Me and @fnmunhoz are working on it :)
